package cli

import (
	_ "embed"
	"fmt"
	"io"
)

// llmsTxtContent is regenerated by: just gen-llms-txt
//
//go:embed llms.txt
var llmsTxtContent string

func printLLMsTxt(w io.Writer) error {
	_, err := fmt.Fprint(w, llmsTxtContent)
	return err
}
